### ISSUE TITLE
Black Sea text renders twice

### ISSUE THREAD

**Issue by maxmeles** [mapbox/mapbox-studio-emerald.tm2#7]
Doesn't look very nice. This happens with a few different map templates, on different zoom levels. Seems to me it occurs only when text is on a line.
![blacksea](https://cloud.githubusercontent.com/assets/1909798/7126446/81ea0794-e239-11e4-9d77-3dda503373a1.jpg)
![blacksea2](https://cloud.githubusercontent.com/assets/1909798/7126447/821a0516-e239-11e4-95f5-05ce8bd7296f.jpg)

**Comment by springmeyer** [comment]
Hi @maxmeles - I agree that this does not look as nice as a single label for would. This is very likely happening because a tile boundary exists between those labels. In other words a single line is used for these labels, but because the maps are rendered via vector tiles the line has been split across tiles and the impact of this is that both tiles get labeled.

We have plans and ideas forming to mitigate this problem, but its not an easy problem to solve. See also https://github.com/mapbox/mapbox-studio/issues/1043 for more discussion.

**Comment by ajashton** [comment]
This problem can be avoided when using `mapbox.mapbox-streets-v6` which the latest version of this style does (you can check out the master branch of this repo and open it in Mapbox Studio to see).

![screenshot from 2015-04-13 18 36 32](https://cloud.githubusercontent.com/assets/126952/7126970/1ab04c82-e20c-11e4-9d4c-f0df12e427d5.png)

**Comment by maxmeles** [comment]
Well all good then, thanks -
